#ifndef NETWORK_TYPES_H
#define NETWORK_TYPES_H

enum NetworkType
{
   NETWORK_MAGIC,
   NETWORK_EMESH_HOP_COUNTER,
   NETWORK_EMESH_HOP_BY_HOP,
   FINITE_BUFFER_NETWORK_EMESH,
   FINITE_BUFFER_NETWORK_CLOS,
   FINITE_BUFFER_NETWORK_ATAC,
   FINITE_BUFFER_NETWORK_FLIP_ATAC,
   NUM_NETWORK_TYPES
};

#endif // NETWORK_TYPES_H
